<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_chimneys_rc-image-tile-33</name>
   <tag></tag>
   <elementGuidId>d0f332b1-7d64-4cd5-badf-d088a2d3ecb7</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='rc-imageselect-target']/table/tbody/tr[3]/td/div/div/img</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>rc-image-tile-33</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://www.google.com/recaptcha/api2/payload?p=06AGdBq27odhd0aGr5blqrz1HvkHjuVgiG5C9H_0EKM-AplJBxpJ92SoaJSMxnxnFwczd_tiwfsm-JPO70qiiBM74U-EzghJcQwXLzOIMv9-HWs9_f-ImMefM8gSlfHnjnct994hAYqbmA_r0AfKCo8st8VL4zxP_BYA4IaD9XwGL9sCRkNAh5MzVxlRDH9Jo6x6H_tBNfBoAOV1xoBcZA8yNNbh7yIWRS9Q&amp;k=6Ld14tkUAAAAAE2Bai2yby8zs3tIVMmKg17bE-PA</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;rc-imageselect-target&quot;)/table[@class=&quot;rc-imageselect-table-33&quot;]/tbody[1]/tr[3]/td[@class=&quot;rc-imageselect-tile&quot;]/div[@class=&quot;rc-image-tile-target&quot;]/div[@class=&quot;rc-image-tile-wrapper&quot;]/img[@class=&quot;rc-image-tile-33&quot;]</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Page_Registrasi Pencari Kost - Mamikos/iframe_html1body1div4div4iframe1_c-c2njj05kxume</value>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='rc-imageselect-target']/table/tbody/tr[3]/td/div/div/img</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>(//img[contains(@src,'https://www.google.com/recaptcha/api2/payload?p=06AGdBq27odhd0aGr5blqrz1HvkHjuVgiG5C9H_0EKM-AplJBxpJ92SoaJSMxnxnFwczd_tiwfsm-JPO70qiiBM74U-EzghJcQwXLzOIMv9-HWs9_f-ImMefM8gSlfHnjnct994hAYqbmA_r0AfKCo8st8VL4zxP_BYA4IaD9XwGL9sCRkNAh5MzVxlRDH9Jo6x6H_tBNfBoAOV1xoBcZA8yNNbh7yIWRS9Q&amp;k=6Ld14tkUAAAAAE2Bai2yby8zs3tIVMmKg17bE-PA')])[7]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[3]/td/div/div/img</value>
   </webElementXpaths>
</WebElementEntity>
