<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_Click verify once there are none left_rc-image-tile-33</name>
   <tag></tag>
   <elementGuidId>2e0a943a-1032-4800-92a2-bdba86d680fe</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='rc-imageselect-target']/table/tbody/tr[2]/td[2]/div/div/img</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>rc-image-tile-33</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://www.google.com/recaptcha/api2/payload?p=06AGdBq26GpVdhZobnJA1HTIbpXV0YWLyeHbsOpUf8TW1tfBoGqOfDC7Fnzr4VVo08K3GsV89XGO1FgyjQJEPgOzfT_d5WLBaqki4pag9s09DXb9DUjjcX9uC1dtsVvBNNeis_C1o68oJhj6tRxVwMt5ZmY6L4240h4VTL07V-Me7BEeE2OUDWWLB6XXx3_SHsxokP8JtzkzhuwKWnT9ifOlkxuyJ2li5PGQ&amp;k=6Ld14tkUAAAAAE2Bai2yby8zs3tIVMmKg17bE-PA</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;rc-imageselect-target&quot;)/table[@class=&quot;rc-imageselect-table-33&quot;]/tbody[1]/tr[2]/td[@class=&quot;rc-imageselect-tile&quot;]/div[@class=&quot;rc-image-tile-target&quot;]/div[@class=&quot;rc-image-tile-wrapper&quot;]/img[@class=&quot;rc-image-tile-33&quot;]</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Page_Registrasi Pencari Kost - Mamikos/iframe_html1body1div4div4iframe1_c-c2njj05kxume</value>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='rc-imageselect-target']/table/tbody/tr[2]/td[2]/div/div/img</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>(//img[contains(@src,'https://www.google.com/recaptcha/api2/payload?p=06AGdBq26GpVdhZobnJA1HTIbpXV0YWLyeHbsOpUf8TW1tfBoGqOfDC7Fnzr4VVo08K3GsV89XGO1FgyjQJEPgOzfT_d5WLBaqki4pag9s09DXb9DUjjcX9uC1dtsVvBNNeis_C1o68oJhj6tRxVwMt5ZmY6L4240h4VTL07V-Me7BEeE2OUDWWLB6XXx3_SHsxokP8JtzkzhuwKWnT9ifOlkxuyJ2li5PGQ&amp;k=6Ld14tkUAAAAAE2Bai2yby8zs3tIVMmKg17bE-PA')])[5]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[2]/td[2]/div/div/img</value>
   </webElementXpaths>
</WebElementEntity>
